name: VeryCoolMinecraftMMORPG
version: '1.0.0'
main: me.randomkitty.verycoolminecraftmmorpg.VeryCoolMinecraftMMORPG
api-version: '1.21'

commands:
  shop:
  openshop:
  spawncustomentity:
  givecustomitem:
  modify:
  fixitem:
  givebook:
  loadspawners:
  loadconfig: